### ISSUE TITLE
All Gantt Charts are Blank

### ISSUE THREAD

**Issue by scamiran** [CodazziS/odoo_addons#10]
I tried to open up a Gantt chart, and for any given project, they all appear blank, with no tasks in view. 

The tasks appear to be correctly setup with deadlines, durations, and start/end times in the gantt settings. They appear correctly in list and kanban view.

**Comment by alyngsoe** [comment]
Same issue here.

**Comment by mlaitinen** [comment]
Could it be because of [this](https://github.com/stephane-/odoo_addons/blob/31d866bbb6a507b060d4b02d5346a6f7fdbd903b/gantt_improvement/static/src/js/gantt.js#L26)? I just noticed that only some of our tasks are visible, and the common denominator is that the gantt start date is before 1st January 2016.

I know the dates are reset in the [init method](https://github.com/stephane-/odoo_addons/blob/31d866bbb6a507b060d4b02d5346a6f7fdbd903b/gantt_improvement/static/src/js/gantt.js#L363), but this is probably some issue in the reconstruction of the gantt chart. If this is the case, I believe #8 is related to this problem.

**Comment by CodazziS** [comment]
Hello, 
I think you have found the problem.
I will try to fix it this week.

Thank for help.

Stéphane

**Comment by mlaitinen** [comment]
Great, thanks! For other participants: a temporary workaround is to edit `gantt.js` and replace

```
def_gantt_date_start: new Date(2015,0,1),   // Dates start for Gantt: Reset in init function
def_gantt_date_end: new Date(2016,0,1),     // Dates stop for Gantt: Reset in init function
```

with

```
def_gantt_date_start: new Date(2016,0,1),   // Dates start for Gantt: Reset in init function
def_gantt_date_end: new Date(2017,0,1),     // Dates stop for Gantt: Reset in init function
```
